name: workspace deployment

on:
    push:
        branches: [ workspace_publish ]
jobs:
    release:
        # You also can use the self-hosted runners.
        runs-on: windows-latest
        steps:
        # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it.
            - uses: actions/checkout@v2
            - name: Synapse workspace deployment
              uses: azure/synapse-workspace-deployment@release-1.0
              with:
                TargetWorkspaceName: 'sw-github-uat'
                TemplateFile: './sw-github-dev/TemplateForWorkspace.json'
                ParametersFile: './sw-github-dev/TemplateParametersForWorkspace.json'
                OverrideArmParameters: './path of the parameters.yaml'
                environment: 'Azure Public'
                resourceGroup: 'swdeshpande'
                clientId: ${{secrets.CLIENTID}}
                clientSecret:  ${{secrets.CLIENTSECRET}}
                subscriptionId:  ${{secrets.SUBSCRIPTIONID}}
                tenantId:  ${{secrets.TENANTID}}
                DeleteArtifactsNotInTemplate: 'true'
                managedIdentity: 'False'
